services:
  - type: web
    name: mucha-casa-api
    runtime: node
    repo: https://github.com/juanpasaflipz/mexican-real-estate-ai
    branch: main
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: BCRYPT_ROUNDS
        value: 10
      - key: JWT_EXPIRE
        value: 7d